// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOHbL5jNqqE7qFAjkV7oHYfe90mFmme1c',
    appId: '1:859033861554:web:633d0ffd9ef992db9fb8ab',
    messagingSenderId: '859033861554',
    projectId: 'devmobilev3',
    authDomain: 'devmobilev3.firebaseapp.com',
    storageBucket: 'devmobilev3.appspot.com',
    measurementId: 'G-BW7BR7S0J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMwm--7gkVZDaSyWaxoGbeNxFd7PxW8is',
    appId: '1:859033861554:android:a8ea6e2c05358b5d9fb8ab',
    messagingSenderId: '859033861554',
    projectId: 'devmobilev3',
    storageBucket: 'devmobilev3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGhECQ5JoSkFkOH-OH8HlLaOSV7czRjyw',
    appId: '1:859033861554:ios:7c7bfa18764552119fb8ab',
    messagingSenderId: '859033861554',
    projectId: 'devmobilev3',
    storageBucket: 'devmobilev3.appspot.com',
    iosBundleId: 'com.example.devmobilev2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGhECQ5JoSkFkOH-OH8HlLaOSV7czRjyw',
    appId: '1:859033861554:ios:7c7bfa18764552119fb8ab',
    messagingSenderId: '859033861554',
    projectId: 'devmobilev3',
    storageBucket: 'devmobilev3.appspot.com',
    iosBundleId: 'com.example.devmobilev2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOHbL5jNqqE7qFAjkV7oHYfe90mFmme1c',
    appId: '1:859033861554:web:76390c7e854704599fb8ab',
    messagingSenderId: '859033861554',
    projectId: 'devmobilev3',
    authDomain: 'devmobilev3.firebaseapp.com',
    storageBucket: 'devmobilev3.appspot.com',
    measurementId: 'G-HRKTE6PL5Y',
  );
}
